project:
  type: website

website:
  title: "Min Sothearith"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sothearith-min
      - icon: linkedin
        href: https://www.linkedin.com/in/sothearith-min/

format:
  html:
    theme: flat
    css: styles.css



